name: Mangalia
favicon: null
layout_spectrum: 0.74535
typography_spectrum: 0.90271
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001d28'
    - '#ffffff'
    - '#473334'
    - '#8e7c64'
    - '#165a92'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.5555517945904285
  rhythmicContrast: 0.5
purpose: []
