layout_spectrum: 0.44013130269013345
typography_spectrum: 0.4893740164116025
color:
  brandColors:
    - '#000100'
    - '#DCE5F4'
    - '#919191'
    - '#EB0A0B'
    - '#2F6B0E'
  brandStrength: 0.4906588641460985
  lightness: 0.5762765423860401
  saturation: 0.16459114477038383
  rhythmicContrast: 0.5593603136949241
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: Saturn
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Mangalia on WEB
description: port turistic
purpose: []
